package gov.daraa.citizen.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequiredDocumentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequiredDocumentAllPropertiesEquals(RequiredDocument expected, RequiredDocument actual) {
        assertRequiredDocumentAutoGeneratedPropertiesEquals(expected, actual);
        assertRequiredDocumentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequiredDocumentAllUpdatablePropertiesEquals(RequiredDocument expected, RequiredDocument actual) {
        assertRequiredDocumentUpdatableFieldsEquals(expected, actual);
        assertRequiredDocumentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequiredDocumentAutoGeneratedPropertiesEquals(RequiredDocument expected, RequiredDocument actual) {
        assertThat(actual)
            .as("Verify RequiredDocument auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequiredDocumentUpdatableFieldsEquals(RequiredDocument expected, RequiredDocument actual) {
        assertThat(actual)
            .as("Verify RequiredDocument relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMandatory()).as("check mandatory").isEqualTo(expected.getMandatory()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequiredDocumentUpdatableRelationshipsEquals(RequiredDocument expected, RequiredDocument actual) {
        assertThat(actual)
            .as("Verify RequiredDocument relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
