package gov.daraa.citizen.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CitizenServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitizenServiceAllPropertiesEquals(CitizenService expected, CitizenService actual) {
        assertCitizenServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertCitizenServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitizenServiceAllUpdatablePropertiesEquals(CitizenService expected, CitizenService actual) {
        assertCitizenServiceUpdatableFieldsEquals(expected, actual);
        assertCitizenServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitizenServiceAutoGeneratedPropertiesEquals(CitizenService expected, CitizenService actual) {
        assertThat(actual)
            .as("Verify CitizenService auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitizenServiceUpdatableFieldsEquals(CitizenService expected, CitizenService actual) {
        assertThat(actual)
            .as("Verify CitizenService relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getEstimatedDuration()).as("check estimatedDuration").isEqualTo(expected.getEstimatedDuration()))
            .satisfies(a ->
                assertThat(a.getEstimatedDurationUnit()).as("check estimatedDurationUnit").isEqualTo(expected.getEstimatedDurationUnit())
            )
            .satisfies(a ->
                assertThat(a.getRequiresPhysicalPresence())
                    .as("check requiresPhysicalPresence")
                    .isEqualTo(expected.getRequiresPhysicalPresence())
            )
            .satisfies(a -> assertThat(a.getIsElectronic()).as("check isElectronic").isEqualTo(expected.getIsElectronic()))
            .satisfies(a -> assertThat(a.getHasSmartCard()).as("check hasSmartCard").isEqualTo(expected.getHasSmartCard()))
            .satisfies(a -> assertThat(a.getFeesDescription()).as("check feesDescription").isEqualTo(expected.getFeesDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCitizenServiceUpdatableRelationshipsEquals(CitizenService expected, CitizenService actual) {
        assertThat(actual)
            .as("Verify CitizenService relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
