package gov.daraa.citizen.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DirectorateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectorateAllPropertiesEquals(Directorate expected, Directorate actual) {
        assertDirectorateAutoGeneratedPropertiesEquals(expected, actual);
        assertDirectorateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectorateAllUpdatablePropertiesEquals(Directorate expected, Directorate actual) {
        assertDirectorateUpdatableFieldsEquals(expected, actual);
        assertDirectorateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectorateAutoGeneratedPropertiesEquals(Directorate expected, Directorate actual) {
        assertThat(actual)
            .as("Verify Directorate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectorateUpdatableFieldsEquals(Directorate expected, Directorate actual) {
        assertThat(actual)
            .as("Verify Directorate relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDirectorateUpdatableRelationshipsEquals(Directorate expected, Directorate actual) {
        // empty method
    }
}
