package gov.daraa.citizen.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceFormTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceFormTemplateAllPropertiesEquals(ServiceFormTemplate expected, ServiceFormTemplate actual) {
        assertServiceFormTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceFormTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceFormTemplateAllUpdatablePropertiesEquals(ServiceFormTemplate expected, ServiceFormTemplate actual) {
        assertServiceFormTemplateUpdatableFieldsEquals(expected, actual);
        assertServiceFormTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceFormTemplateAutoGeneratedPropertiesEquals(ServiceFormTemplate expected, ServiceFormTemplate actual) {
        assertThat(actual)
            .as("Verify ServiceFormTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceFormTemplateUpdatableFieldsEquals(ServiceFormTemplate expected, ServiceFormTemplate actual) {
        assertThat(actual)
            .as("Verify ServiceFormTemplate relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getFile()).as("check file").isEqualTo(expected.getFile()))
            .satisfies(a -> assertThat(a.getFileContentType()).as("check file contenty type").isEqualTo(expected.getFileContentType()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getOrderIndex()).as("check orderIndex").isEqualTo(expected.getOrderIndex()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceFormTemplateUpdatableRelationshipsEquals(ServiceFormTemplate expected, ServiceFormTemplate actual) {
        assertThat(actual)
            .as("Verify ServiceFormTemplate relationships")
            .satisfies(a -> assertThat(a.getService()).as("check service").isEqualTo(expected.getService()));
    }
}
