package gov.daraa.citizen.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServiceCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceCategoryAllPropertiesEquals(ServiceCategory expected, ServiceCategory actual) {
        assertServiceCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertServiceCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceCategoryAllUpdatablePropertiesEquals(ServiceCategory expected, ServiceCategory actual) {
        assertServiceCategoryUpdatableFieldsEquals(expected, actual);
        assertServiceCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceCategoryAutoGeneratedPropertiesEquals(ServiceCategory expected, ServiceCategory actual) {
        assertThat(actual)
            .as("Verify ServiceCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceCategoryUpdatableFieldsEquals(ServiceCategory expected, ServiceCategory actual) {
        assertThat(actual)
            .as("Verify ServiceCategory relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServiceCategoryUpdatableRelationshipsEquals(ServiceCategory expected, ServiceCategory actual) {
        assertThat(actual)
            .as("Verify ServiceCategory relationships")
            .satisfies(a -> assertThat(a.getDirectorate()).as("check directorate").isEqualTo(expected.getDirectorate()));
    }
}
